const boletoTemplate = [
  'header-image',
  'text-introduction',
  'outer-separator',
  'refund-title',
  'field-transaction-id',
  'separator',
  'field-date-created',
  'separator',
  'field-amount',
  'separator',
  'field-refunded-amount',
  'separator',
  'field-date-refunded',
  'favored-title',
  'field-bank-account-legal-name',
  'separator',
  'field-bank-account-document',
  'separator',
  'field-bank-account-name',
  'separator',
  'field-bank-account-agency',
  'separator',
  'field-bank-account-number',
  'separator',
  'field-bank-account-type',
  'farewell',
  'outer-separator',
  'footer',
]

const creditCardTemplate = [
  'header-image',
  'text-introduction',
  'outer-separator',
  'refund-title',
  'field-transaction-id',
  'separator',
  'field-authorization-id',
  'separator',
  'field-date-created',
  'separator',
  'field-amount',
  'separator',
  'field-refunded-amount',
  'separator',
  'field-date-refunded',
  'favored-title',
  'field-card-holder-name',
  'separator',
  'field-card-number',
  'separator',
  'field-card-brand',
  'warning-credit-card',
  'farewell',
  'outer-separator',
  'footer',
  'field-bank-account-document',
  'separator',
]

const getReceiptTemplate = paymentMethod => (paymentMethod === 'boleto'
  ? boletoTemplate
  : creditCardTemplate)

export default getReceiptTemplate
